---
# PHYTEC EEPROM Flashtool Config File
# product: PCL-070 / phyCORE-i.MX8 MP
# Copyright (C) 2019-2025 PHYTEC

PHYTEC:
  eeprom_offset: 0x0
  i2c_bus: 0
  i2c_dev: 0x51
  extended_options: 1
  optiontree_rev: 0

Kit:
  0: Processor
  1: CAN FD / VPU / ISP / NPU
  2: DDR-Ram
  3: eMMC
  4: NOR-Flash
  5: Coating / RTC / Optional Connector / Ethernet
  6: Temperature
  7: Temperature Sensor
Processor:
  '0': Quad Core 1.6 GHz
  '1': Quad Core 1.8 GHz
  '2': Dual Core 1.6 GHz
  '3': Dual Core 1.8 GHz
CAN FD / VPU / ISP / NPU:
  '0': CAN / - / - / -
  '1': CAN / - / - / NPU
  '2': CAN / - / ISP / -
  '3': CAN / - / ISP / NPU
  '4': CAN / VPU / - / -
  '5': CAN / VPU / - / NPU
  '6': CAN / VPU / ISP / -
  '7': CAN / VPU / ISP / NPU
  '8': CAN-FD / - / - / -
  '9': CAN-FD / - / - / NPU
  A: CAN-FD / - / ISP / -
  B: CAN-FD / - / ISP / NPU
  C: CAN-FD / VPU / - / -
  D: CAN-FD / VPU / - / NPU
  E: CAN-FD / VPU / ISP / -
  F: CAN-FD / VPU / ISP / NPU
DDR-Ram:
  '0': 256 MB
  '1': 512 MB
  '2': 1 GB  (2 GHz)
  '3': 2 GB  (2 GHz)
  '4': 3 GB
  '5': 4 GB  (1.5 GHz)
  '6': 6 GB
  '7': 8 GB
  '8': 4 GB (2 GHz)
eMMC:
  '0': '-'
  '1': 4 GB (MLC)
  '2': 8 GB (MLC)
  '3': 16 GB (MLC)
  '4': 32 GB (MLC)
  '5': 64 GB (MLC)
  '6': 40 GB (pSLC)
NOR-Flash:
  '0': '-'
  '1': 8 MB
  '2': 16 MB
  '3': 32 MB
  '4': 64 MB
  '5': 128 MB
  '6': 256 MB
Coating / RTC / Optional Connector / Ethernet:
  '0': '- / External RTC / - / -'
  '1': '- / External RTC / - / Gbit Ethernet Phy'
  '2': '- / External RTC / Optional Connector mounted / -'
  '3': '- / External RTC / Optional Connector mounted / Gbit Ethernet Phy'
  '4': '- / - / - / -'
  '5': '- / - / - / Gbit Ethernet Phy'
  '6': '- / - / Optional Connector mounted / -'
  '7': '- / - / Optional Connector mounted / Gbit Ethernet Phy'
  '8': Coated / External RTC / - / -
  '9': Coated / External RTC / - / Gbit Ethernet Phy
  A: Coated / External RTC / Optional Connector mounted / -
  B: Coated / External RTC / Optional Connector mounted / Gbit Ethernet Phy
  C: Coated / - / - / -
  D: Coated / - / - / Gbit Ethernet Phy
  E: Coated / - / Optional Connector mounted / -
  F: Coated / - / Optional Connector mounted / Gbit Ethernet Phy
Temperature:
  C: Consumer Temp
  I: Industrial Temp
  X: Extended Consumer Temp
Temperature Sensor:
  '0': '-'
  '1': Temperature Sensor
