---
# PHYTEC EEPROM Flashtool Config File
# product: PCL-069 / phyCORE-i.MX8 MM
# Copyright (C) 2020-2025 PHYTEC

PHYTEC:
  eeprom_offset: 0x0
  i2c_bus: 0
  i2c_dev: 0x51
  extended_options: 1
  optiontree_rev: 0

Kit:
  0: Processor (Mini)
  1: Processor (Nano)
  2: DDR-Ram
  3: eMMC
  4: NOR-Flash
  5: Ethernet
  6: Display Option
  7: Temperature
  8: Coating
Processor (Mini):
  '0': '- (Nano)'
  '1': Quad Core 1.6 GHz (with VPU, Consumer 1.8 GHz)
  '2': Quad Core Lite 1.6 GHz (without VPU, Consumer 1.8 GHz)
  '3': Dual Core 1.6 GHz (with VPU, Consumer 1.8 GHz)
  '4': Dual Core Lite 1.6 GHz (without VPU, Consumer 1.8 GHz)
  '5': Single Core 1.6 GHz (with VPU, Consumer 1.8 GHz)
  '6': Single Core Lite 1.6 GHz (without VPU, Consumer 1.8 GHz)
  '7': Quad Core Lite 1.8 GHz (without VPU, Immersiv3D, Consumer only)
  '8': Quad Core Lite 1.8 GHz (without VPU, Immersiv3D+Dolby Atmos, Consumer only)
  '9': Quad Core Lite 1.8 GHz (without VPU, Immersiv3D+Dolby Atmos+DTS, Consumer only)
  A: Quad Core Lite 1.8 GHz (without VPU, Immersiv3D+Dolby Atmos+AC4, Consumer only)
Processor (Nano):
  '0': '- (Mini)'
  '1': Quad Core 1.4 GHz (with GPU, Consumer 1.5 GHz)
  '2': Quad Core Lite 1.4 GHz (without GPU, Consumer 1.5 GHz)
  '3': Dual Core 1.4 GHz (with GPU, Consumer 1.5 GHz)
  '4': Dual Core Lite 1.4 GHz (without GPU, Consumer 1.5 GHz)
  '5': Single Core 1.4 GHz (with GPU, Consumer 1.5 GHz)
  '6': Single Core Lite 1.4 GHz (without GPU, Consumer 1.5 GHz)
  '7': Quad Core 1.5 GHz (with GPU, Immersiv3D+Dolby Atmos, Consumer only)
DDR-Ram:
  '0': 512 MB
  '1': 1 GB
  '2': 1.5 GB
  '3': 2 GB
  '4': 3 GB
  '5': 4 GB
eMMC:
  '0': '-'
  '1': 4 GB (MLC)
  '2': 8 GB (MLC)
  '3': 16 GB (MLC)
  '4': 32 GB (MLC)
  '5': 64 GB (MLC)
  '6': 128 GB (MLC)
  '7': 256 GB (MLC)
NOR-Flash:
  '0': '-'
  '1': 4 MB
  '2': 16 MB
  '3': 32 MB
  '4': 64 MB
Ethernet:
  '0': '-  (RGMII on connector)'
  '1': Gbit Ethernet Phy
  '3': Gbit Ethernet Phy (ADIN)
Display Option:
  '0': MIPI DSI
  '1': LVDS (TI Chip)
  '2': no display interface
  '3': LVDS Alternative (Toshiba Chip)
Temperature:
  C: Consumer Temp
  I: Industrial Temp
  X: Extended Consumer Temp
Coating:
  '0': '-'
  L: Coated
