---
# PCM-057 PHYTEC EEPROM Flashtool Config File
# Copyright (C) 2019-2020 PHYTEC

PHYTEC:
  eeprom_offset: 0x0
  eth_name: 'eth0'
  i2c_bus: 0
  i2c_dev: 0x50
  ep_encoding: '6B17s2s6xB'
# ep_encoding_format:
# 6 uchars, 17-len str, 2-len str, 6-len pad, 1 uchar

Kit:
  0: DDR-Ram
  1: ECC RAM Bank 1
  2: NAND/eMMC
  3: NOR-Flash
  4: Processor
  5: EEPROM
  6: Ethernet
  7: RTC
  8: Temperature
DDR-Ram:
  '0': 512 MB (1 Bank)
  '1': 1 GB (1 Bank)
  '2': 1 GB (2 Banks)
  '3': 2 GB (1 Bank)
  '4': 2 GB (2 Banks)
  '5': 4 GB (2 Banks)
ECC RAM Bank 1:
  '0': No ECC
  '1': With ECC (8 bit, 256 MB, for Bank 1)
  '2': With ECC (8 bit, 512 MB, for Bank1)
NAND/eMMC:
  '0': '-'
  '1': 2 GB eMMC (MLC)
  '2': 4 GB eMMC (MLC)
  '3': 8 GB eMMC (MLC)
  '4': 16 GB eMMC (MLC)
  '5': 32 GB eMMC (MLC)
  '6': 256 MB NAND (8 bit)
  '7': 256 MB NAND (16 bit)
  '8': 512 MB NAND (8 bit)
  '9': 512 MB NAND (16 bit)
  A: 1 GB NAND (8 bit)
  B: 1 GB NAND (16 bit)
  C: 2 GB NAND (8 bit)
  D: 2 GB NAND (16 bit)
NOR-Flash:
  '0': '-'
  '1': 16 MB
Processor:
  '0': Dual Core 1.5 GHz (Graphics, AM5728)
  '1': Dual Core 1.5 GHz (AM5726)
  '2': Dual Core 1.5 GHz (Graphics, EVE, AM5749)
  '3': Single Core 1.5 GHz (AM5716)
  '4': Dual Core 1.5 GHz (Graphics, AM5748)
  '5': Dual Core 1.5 GHz (AM5746)
  '6': Dual Core 1.5 GHz (Graphics, AM5729)
EEPROM:
  '0': '-'
  '1': 4 kB
Ethernet:
  '0': '-'
  '1': Gbit Ethernet Phy
RTC:
  '0': '-'
  '1': External RTC
Temperature:
  C: Consumer Temp
  I: Industrial Temp
