---
# PHYTEC EEPROM Flashtool Config File
# product: PCM-071 / phyCORE-AM62x
# Copyright (C) 2019-2025 PHYTEC

PHYTEC:
  eeprom_offset: 0x0
  i2c_bus: 0
  i2c_dev: 0x50
  api: 3
  max_image_size: 2048

Kit:
  0: 3D Graphics Engine
  1: Processor
  2: Additional Processor Features
  3: DDR-Ram
  4: eMMC
  5: NOR-Flash
  6: Ethernet
  7: RTC
  8: Temperature
3D Graphics Engine:
  '3': 'No'
  '5': 'Yes'
Processor:
  '1': Single Core
  '2': Dual Core
  '4': Quad Core
Additional Processor Features:
  '0': Low Speed, no PRU
  '1': Low Speed, PRU
  '2': High Speed, no PRU
  '3': High Speed, PRU
DDR-Ram:
  '0': 512 MB
  '1': 1 GB
  '2': 2 GB
  '4': 4 GB
eMMC:
  A: 4 GB (MLC)
  B: 8 GB (MLC)
  C: 16 GB (MLC)
  D: 32 GB (MLC)
  E: 64 GB (MLC)
  F: 128 GB (MLC)
  X: '-'
NOR-Flash:
  A: 16 MB (Quad)
  B: 32 MB (Quad)
  C: 64 MB (Quad)
  D: 32 MB (Octal)
  E: 64 MB (Octal)
  F: 128 MB (Octal)
  X: '-'
Ethernet:
  '0': '-'
  '1': Gbit Ethernet Phy
  A: 10/100 Mbit
RTC:
  '0': '-'
  '1': External RTC
Temperature:
  C: Consumer Temp
  I: Industrial Temp
