---
# PCM-057 PHYTEC EEPROM Flashtool Config File
# Copyright (C) 2019-2020 PHYTEC

PHYTEC:
  eeprom_offset: 0x0
  eth_name: 'eth0'
  i2c_bus: 0
  i2c_dev: 0x50
  ep_encoding: '6B17s2s6xB'
# ep_encoding_format:
# 6 uchars, 17-len str, 2-len str, 6-len pad, 1 uchar

Kit:
  0: DDR
  1: ECC
  2: eMMC/NAND
  3: SPI
  4: Controller
  5: EEPROM
  6: Ethernet
  7: RTC
  8: Temp

DDR:
  '0': 512MB DDR3 RAM 1 Bank
  '1': 1GB DDR3 RAM 1 Bank
  '2': 1GB DDR3 RAM 2 Banks
  '3': 2GB DDR3 RAM 1 Bank
  '4': 2GB DDR3 RAM 2 Banks
  '5': 4GB DDR3 RAM 2 Banks

ECC:
  '0': No ECC
  '1': 256MB 8-bit ECC RAM (Bank 1)
  '2': 512MB 8-bit ECC RAM (Bank 1)

eMMC/NAND:
  '0': No eMMC/NAND
  '2': 4GB eMMC
  '3': 8GB eMMC
  '4': 16GB eMMC
  '5': 32GB eMMC
  'A': 1GB 8-bit NAND

SPI:
  '0': No SPI NOR Flash
  '1': 16MB SPI NOR Flash

Controller:
  '0': TI AM5728 Controller
  '1': TI AM5726 Controller
  '2': TI AM5749 Controller
  '3': TI AM5716 Controller
  '4': TI AM5748 Controller
  '5': TI AM5746 Controller
  '6': TI AM5729 Controller

EEPROM:
  '0': No EEPROM
  '1': 4KB EEPROM

Ethernet:
  '0': No ethernet
  '1': 10/100/1000 ethernet PHY

RTC:
  '0': No Real-Time Clock
  '1': Real-Time Clock

Temp:
  'I': Industrial -40C to +85C
  'C': Commercial 0C to +85C
