---
# PHYTEC EEPROM Flashtool Config File
# product: PFL-G-03.yml / phyFLEX-AM62Lx
# Copyright (C) 2025 PHYTEC

PHYTEC:
  eeprom_offset: 0x0
  i2c_bus: 0x1
  i2c_dev: 0x50
  api: 3
  extended_options: 1
  max_image_size: 1024
  optiontree_rev: 0
Kit:
  0: Processor
  1: Frequency A53
  2: Reserved 1
  3: DDR-Ram
  4: eMMC
  5: Display Option (DSI0)
  6: Ethernet
  7: Temperature Sensor / RTC
  8: Temperature
  9: IO Voltage (VCC_IO) / Additional Voltage Supply Feature (Monoflop) / eFuse
Processor:
  '1': Single Core
  '2': Dual Core
Frequency A53:
  '0': 800 MHz
  '1': 1.25 GHz
Reserved 1:
  '0': Always 0
DDR-Ram:
  '0': 512 MB
  '1': 1 GB
  '2': 2 GB
  '3': 4 GB
eMMC:
  '0': '-'
  '1': 4 GB (MLC)
  '2': 8 GB (MLC)
  '3': 16 GB (MLC)
  '4': 32 GB (MLC)
  '5': 64 GB (MLC)
  '6': 128 GB (MLC)
Display Option (DSI0):
  '0': MIPI DSI
  '1': LVDS
Ethernet:
  '0': '-'
  '1': Gbit Ethernet Phy
Temperature Sensor / RTC:
  '0': '- / -'
  '1': '- / External RTC'
  '8': Temperature Sensor / -
  '9': Temperature Sensor / External RTC
Temperature:
  A: Automotive Temp
  C: Consumer Temp
  I: Industrial Temp
IO Voltage (VCC_IO) / Additional Voltage Supply Feature (Monoflop) / eFuse:
  '0': 1.8 V / powercycle on reset / not programmable
  '1': 1.8 V / powercycle on reset / programmable in field
  '2': 1.8 V / no powercycle on reset / not programmable
  '3': 1.8 V / no powercycle on reset / programmable in field
  '4': 3.3 V / powercycle on reset / not programmable
  '5': 3.3 V / powercycle on reset / programmable in field
  '6': 3.3 V / no powercycle on reset / not programmable
  '7': 3.3 V / no powercycle on reset / programmable in field
