# PCL-066 PHYTEC EEPROM Flashtool Config File
# board: imx8mq phyboard polaris
# Copyright (C) 2019 PHYTEC

PHYTEC:
  eeprom_offset: 0
  eth_name: eth0
  i2c_bus: 0
  i2c_dev: 5a
  kit_options: 8
  ep_encoding: '4B10s11x6xB'
#ep_encoding-format: 4 uchars, 10-len str, 11-len pad, 6-len pad/str, 1 uchar

Kit:
  0: Controller
  1: Taktrate
  2: DDR
  3: eMMC
  4: Quad SPI Nor
  5: Ethernet
  6: WLAN
  7: Temp

Known:
  3022210I: A0
  3032210I: A0
  1112010C: A0
  4054211I: A0
  3112011I: A0
  3133111I: A0

Controller:
  '0': Quad Lite (GPU, No VPU) IMX8MQ5
  '1': Dual (VPU decode + HDR10 + GPU) IMX8MD6
  '2': Dual (VPU decode + Dolby Vision + HDR10 + GPU) IMX8MD7
  '3': Quad (VPU decode + HDR10 + GPU) IMX8MQ6
  '4': Quad (VPU decode + Dolby Vision + HDR10 + GPU) IMX8MQ7

Taktrate:
  '0': 1.3GHz
  '1': 1.5GHz

DDR:
  '0': 512MB DDR4 RAM 1 Bank
  '1': 1GB DDR4 RAM 1 Bank
  '2': 1.5GB DDR4 RAM 1 Bank
  '3': 2GB DDR4 RAM 1 Bank
  '4': 3GB DDR4 RAM 1 Bank
  '5': 4GB DDR4 RAM 1 Bank
  '6': 6GB DDR4 RAM 1 Bank
  '7': 8GB DDR4 RAM 1 Bank

eMMC:
  '0': No eMMC
  '1': 4GB eMMC
  '2': 8GB eMMC
  '3': 16GB eMMC
  '4': 32GB eMMC
  '5': 64GB eMMC (only Commercial)

Quad SPI Nor:
  '0': no SPI-Nor
  '1': 4MB
  '2': 16MB
  '3': 32MB
  '4': 64MB

Ethernet:
  '0': RGMII
  '1': 10/100/1000 ethernet PHY

WLAN:
  '0': No WLAN
  '1': WLAN/Bluetooth Sterling Module

Temp:
  C: Commercial 0C to +70C
  I: Industrial -40C to +85C

ep:
  api_version: None
  som_pcb_rev: None
  ksp: None
  kspno: None
  kit_opt: None
  hw8: None
